__author__ = 'mnowotka'

from django.db import models
from chembl_core_model.models import *
from chembl_core_db.db.customFields import BlobField, ChemblCharField
from chembl_core_db.db.models.abstractModel import ChemblAbstractModel
from chembl_core_db.db.models.abstractModel import ChemblModelMetaClass
from django.utils import six

# ----------------------------------------------------------------------------------------------------------------------


class UcSource(six.with_metaclass(ChemblModelMetaClass, ChemblAbstractModel)):

    NUMBER_OR_DATE_CHOICES = (
        ('date', 'date'),
        ('number', 'number'),
        )

    SRC_CLASS_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        )

    src_id = ChemblPositiveIntegerField(length=2, primary_key=True, help_text=u'Unique ID for source (generated by UniChem, ie: an internal ID)')
    name = ChemblCharField(max_length=50, blank=True, null=True, help_text=u'Name of source')
    description = ChemblCharField(max_length=2000, blank=True, null=True, help_text=u'Description of this source.')
    current_release_u = ChemblPositiveIntegerField(length=2, blank=True, null=True, help_text=u'Current unichem release number (assigned by unichem) of this source')
    created = ChemblDateField(blank=True, null=True, help_text=u'Date this record was created')
    last_updated = ChemblDateField(blank=True, null=True, help_text=u'Date this record was last updated')
    userstamp = ChemblCharField(max_length=20, blank=True, null=True, help_text=u'The user who last updated this record')
    number_or_date = ChemblCharField(max_length=20, blank=True, null=True, choices=NUMBER_OR_DATE_CHOICES, help_text=u'Does this source version data releases by date or by number')
    name_long = ChemblCharField(max_length=2000, blank=True, null=True, help_text=u'Name of Source. Longer form for presentation.')
    src_details = ChemblCharField(max_length=2000, blank=True, null=True, help_text=u'Technical details of how the data was/is obtained from the source. Note, more detailed info for each release can be found in UC_RELEASE.MISC')
    src_url = ChemblCharField(max_length=2000, blank=True, null=True, help_text=u'The Home Page URL for the source')
    base_id_url = ChemblCharField(max_length=2000, blank=True, null=True, help_text=u"The base url for the src_compound_id in the source. If 'null', then this source does not support direct links to src_compound_id pages. If not null, simply append src_compound_id to end of this string to create full url if base_id_url available = 1. If base_url_id_available = 0, then a more complex manipulation of base_id_url and src_compound_id is required (managed in interface)")
    base_id_url_available = ChemblNullableBooleanField(help_text=u"May the src_compound_id simply be appended to the base_url_id to create a valid url to a unique page for the src_compound_id ? 1 = yes, 0 = no, a more complex manipulation may be required to create the url. This field ignorred in interface if base_url_id is 'null'")
    aux_required = ChemblNullableBooleanField(help_text=u'Auxilliary information for each src-compound_id is required to be captured at load time for this source [col4 of input file], and stored in UC_XREF.AUX_SRC')
    aux_for_url = ChemblNullableBooleanField(help_text=u'Does the auxiliary information get used to create the URL instead of the src_compound_id ?')
    aux_description = ChemblCharField(max_length=4000, blank=True, null=True, help_text=u'If Auxiliary information is required (ie: if 1 in AUX_REQUIRED field), what is it required FOR, and how should it be processed ? Note: if AUX_FOR_URL = 1, then aux information is used to create the URL instead of the src_compound_id')
    private = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'A flag to indicate whether data from this source is private (1) or can be made public (0)')
    name_label = ChemblCharField(max_length=200, blank=True, null=True, help_text=u'The name of the source, with spacing and case of text as in the source itself. Suitable for use as a label in hyperlinks. Always less than 30 characters.')
    src_class = ChemblPositiveIntegerField(length=38, blank=True, null=True, choices=SRC_CLASS_CHOICES, help_text=u'Class of the source. FK to UC_SRC_CLASS.CLASS_ID')
    keys_only = ChemblNullableBooleanField(help_text=u'Source has only InChIKeys, as InChIs are not made available. 1=yes, 0 or null = no')
    update_min = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'The minimum number of days before which an update can be expected. Do not bother trying to update this source if days from last release is smaller than this.')
    update_opt = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'The optimal number of days between releases (ie: you can expect a new release to be available if the days since the last release equals this number) ')
    update_max = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'The maximum number of days after which an update can be considered very overdue.')
    update_j = ChemblNullableBooleanField(help_text=u'Are incremental updates appropriate for this source (1=yes, 0=no)')
    update_comments = ChemblCharField(max_length=500, blank=True, null=True, help_text=u'A comment on the reasons behind the settings used for other UPDATE_ columns in this table.')
    synonyms = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'The number of synonyms captured from this source, and available in UC_SYNONYMS table.')

    class Meta:
        app_label = 'unistruct'
        managed = False

# ----------------------------------------------------------------------------------------------------------------------


class UcStructure(six.with_metaclass(ChemblModelMetaClass, ChemblAbstractModel)):

    uci = ChemblCharField(primary_key=True, max_length=20, help_text=u'UniChem Identifier')
    standardinchi = ChemblCharField(max_length=4000, unique=True, blank=True, null=True, help_text=u'The standard Inchi assigned to this UCI')
    standardinchikey = ChemblCharField(max_length=30, unique=True, blank=True, null=True, help_text=u'The Standard Inchi Key generated from the Standard Inchi field.')
    created = ChemblDateField(blank=True, null=True, help_text=u'Date this record was first created')
    username = ChemblCharField(max_length=20, blank=True, null=True, help_text=u'Name of user who created this record.')
    fikhb = ChemblCharField(max_length=14, db_index=True, blank=True, null=True, help_text=u'First InchKey Hash Block. 14 letters that appear at the start of the InChiKey. Denotes the connectivity of the inchi')

    class Meta:
        app_label = 'unistruct'
        managed = False

#-----------------------------------------------------------------------------------------------------------------------


class UcRelease(six.with_metaclass(ChemblModelMetaClass, ChemblAbstractModel)):

    src = models.OneToOneField(UcSource, primary_key=True, help_text=u'Foreign key to SRC_ID in UC_SOURCE')
    release_u = ChemblNoLimitDecimalField(primary_key=True, help_text=u'The UniChem assigned release number of this data release, for this source - may be different to release numbers or dates assigned by the source')
    created = ChemblDateField(blank=True, null=True, help_text=u'The date that this record was created.')
    src_release_number = ChemblNoLimitDecimalField(blank=True, null=True, help_text=u'The release number (if any) assigned by the source (src) for this data release.')
    src_release_date = ChemblDateField(blank=True, null=True, help_text=u'The release date, if no SRC_RELEASE_NUMBER available, as supplied by the source src.')
    userstamp = ChemblCharField(max_length=20, blank=True, null=True, help_text=u'The user who created this record.')
    records_without_comments = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'Number of records loaded without comments.')
    records_with_comments = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'Number of records loaded with comments. Comments in UC_RELEASE_LOGs.')
    records_ignored = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'Number of records ignored (ie: NOT loaded).  Comments in UC_RELEASE_LOGs.')
    number_of_new_ucis = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'Number of new UCIs generated when this release was loaded.')
    uc_load_index = ChemblPositiveIntegerField(length=38, blank=True, null=True, help_text=u'Data Release Load Number (order in which data releases were loaded into UniChem)')
    misc = ChemblCharField(max_length=4000, blank=True, null=True)

    class Meta:
        unique_together = (("src", "release_u"),)
        app_label = 'unistruct'
        managed = False

# ----------------------------------------------------------------------------------------------------------------------


class UcXref(six.with_metaclass(ChemblModelMetaClass, ChemblAbstractModel)):

    uci = models.OneToOneField(UcStructure, primary_key=True, db_column='uci', help_text=u'Foreign key to UCI in UC_STRUCTURE')
    src = models.OneToOneField(UcSource, primary_key=True, help_text=u'Foreign key to SRC_ID in UC_SOURCE')
    src_compound_id = ChemblCharField(primary_key=True, max_length=400, help_text=u'ID of compound as defined in source.')
    assignment = ChemblNullableBooleanField(help_text=u'Flag to indicate whether this assignment of src_compound_id to UCI is CURRENT [1], or is OBSOLETE [0]. ie is this assignment true in the current release.')
    last_release_u_when_current = ChemblNoLimitDecimalField(blank=True, null=True, help_text=u'For obsolete assignments, UniChem release number where ASSIGNMENT was last CURRENT. Note, this release number refers to the release_u, ie the release number assigned by unichem')
    created = ChemblDateField(blank=True, null=True, help_text=u'Date this record was first created.')
    lastupdated = ChemblDateField(blank=True, null=True, help_text=u'Date this record was last updated [NB Only update permitted is the changing of CURRENT to OBSOLETE together with the changing of last_release_when_current from null to a version number]')
    userstamp = ChemblCharField(max_length=20, blank=True, null=True, help_text=u'User who last updated this record.')
    aux_src = ChemblCharField(max_length=4000, blank=True, null=True, help_text=u'Auxiliary information associated with this src_compound_id')

    class Meta:
        unique_together = (("uci", "src", "src_compound_id"),)
        app_label = 'unistruct'
        managed = False

# ----------------------------------------------------------------------------------------------------------------------
